name: CI/CD Pipeline - Medplus App

on:
  push:
    branches:
      - main

jobs:
  build-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 209888747223.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build, Tag, and Push Image to Amazon ECR
        run: |
          IMAGE_TAG=${{ github.run_number }}
          IMAGE_URI=209888747223.dkr.ecr.eu-north-1.amazonaws.com/mediplus:${IMAGE_TAG}
          echo "Building Docker image..."
          docker build -t $IMAGE_URI .
          echo "Pushing image to ECR..."
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

  deploy:
    name: Deploy to EC2
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            IMAGE_URI=209888747223.dkr.ecr.eu-north-1.amazonaws.com/mediplus:${{ github.run_number }}
            echo "Logging into ECR..."
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 209888747223.dkr.ecr.eu-north-1.amazonaws.com

            echo "Pulling latest image..."
            docker pull $IMAGE_URI

            echo "Stopping old container (if running)..."
            docker stop mediplus-container || true
            docker rm mediplus-container || true

            echo "Running new container..."
            docker run -d -p 80:80 --name mediplus-container $IMAGE_URI

            echo "Deployment complete!"

  update-k8-yaml:
    name: Update Kubernetes Manifest Repo
    runs-on: ubuntu-latest
    needs: deploy  
    steps:
      - name: Clone K8s YAML repository
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: |
          git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/Ifeanyi-Christian/kubernetes-manifest-yaml.git
          cd kubernetes-manifest-yaml

          echo "Updating image in deployment.yaml..."
          sed -i "s|209888747223.dkr.ecr.eu-north-1.amazonaws.com/mediplus:.*|209888747223.dkr.ecr.eu-north-1.amazonaws.com/mediplus:${{ github.run_number }}|g" deployment.yaml

          git config user.email "okwuigboifeanyichristian@gmail.com"
          git config user.name "$GIT_USERNAME"

          git add deployment.yaml
          git commit -m "Updated mediplus image to tag ${{ github.run_number }}"
          git push https://$GIT_USERNAME:$GIT_PASSWORD@github.com/Ifeanyi-Christian/kubernetes-manifest-yaml.git HEAD:main


